name: bitswap

# train
lr : 0.002
epochs : 100000
num_workers : 8
batch_size : 1024

gpus : 4
# data
dataset : img224
use_amp : 0

swa_epoch_start: 0

optimizer: adamw
scheduler: multistep
scheduler_interval: epoch

